services:
  - docker

before_install:
  - docker build -t doc-build .
  - chmod +x docker-run.sh
  - chmod +x build.sh
  - chmod +x travis-validation.sh

install: true

script: 
  - ./travis-validation.sh
  - ./docker-run.sh

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: artifacts
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  repo: PlatformOfTrust/standards
  on:
    branch: master
